In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("breast-cancer-wisconsin-data.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (569, 32)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Rows: 569
Columns: 32

Column names:
['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 'concave points_worst', 'symmetry_worst', 'fractal_dimension_worst']

Data types:
id                           int64
diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

Missing values:
0

Duplicate rows:
0

In [6]:
print(df["diagnosis"].value_counts())

diagnosis
B    357
M    212
Name: count, dtype: int64

In [8]:
print(df["diagnosis"].value_counts(normalize=True) * 100)

diagnosis
B    62.741652
M    37.258348
Name: proportion, dtype: float64

In [10]:
df = df.drop(columns=["id"])

In [12]:
print(df.shape)

(569, 31)

In [14]:
df["diagnosis"] = df["diagnosis"].map({"B": 0, "M": 1})

In [16]:
print(df["diagnosis"].value_counts())

diagnosis
0    357
1    212
Name: count, dtype: int64

In [18]:
# Separate features and target

X = df.drop(columns=["diagnosis"])
y = df["diagnosis"]

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (569, 30)
Shape of y: (569,)

In [20]:
print(X.head())

   radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840
1        20.57         17.77          132.90     1326.0          0.08474
2        19.69         21.25          130.00     1203.0          0.10960
3        11.42         20.38           77.58      386.1          0.14250
4        20.29         14.34          135.10     1297.0          0.10030

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419
1           0.07864          0.0869              0.07017         0.1812
2           0.15990          0.1974              0.12790         0.2069
3           0.28390          0.2414              0.10520         0.2597
4           0.13280          0.1980              0.10430         0.1809

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60
1                 0.05667  ...         24.99          23.41           158.80
2                 0.05999  ...         23.57          25.53           152.50
3                 0.09744  ...         14.91          26.50            98.87
4                 0.05883  ...         22.54          16.67           152.20

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119
1      1956.0            0.1238             0.1866           0.2416
2      1709.0            0.1444             0.4245           0.4504
3       567.7            0.2098             0.8663           0.6869
4      1575.0            0.1374             0.2050           0.4000

   concave points_worst  symmetry_worst  fractal_dimension_worst
0                0.2654          0.4601                  0.11890
1                0.1860          0.2750                  0.08902
2                0.2430          0.3613                  0.08758
3                0.2575          0.6638                  0.17300
4                0.1625          0.2364                  0.07678

[5 rows x 30 columns]

In [22]:
print(X.dtypes.value_counts())

float64    30
Name: count, dtype: int64

In [24]:
print("Missing values in X:", X.isnull().sum().sum())

Missing values in X: 0

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (455, 30)
X_test : (114, 30)
y_train: (455,)
y_test : (114,)

In [28]:
print("Training target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Training target distribution:
diagnosis
0    285
1    170
Name: count, dtype: int64

Testing target distribution:
diagnosis
0    72
1    42
Name: count, dtype: int64

In [30]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler = StandardScaler()

In [34]:
X_train_scaled = scaler.fit_transform(X_train)

In [36]:
X_test_scaled = scaler.transform(X_test)

In [38]:
print("Scaled X_train:", X_train_scaled.shape)
print("Scaled X_test :", X_test_scaled.shape)

Scaled X_train: (455, 30)
Scaled X_test : (114, 30)

In [40]:
X_train_scaled = scaler.fit_transform(X_train)

In [42]:
X_test_scaled = scaler.transform(X_test)

In [44]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("Scaled X_train:", X_train_scaled.shape)
print("Scaled X_test :", X_test_scaled.shape)

X_train: (455, 30)
X_test : (114, 30)
Scaled X_train: (455, 30)
Scaled X_test : (114, 30)

Logistic Regression -First classification model.

In [46]:
from sklearn.linear_model import LogisticRegression

In [48]:
logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [50]:
logistic_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [52]:
y_pred_logistic = logistic_model.predict(X_test_scaled)

In [54]:
print("First 10 predicted values:")
print(y_pred_logistic[:10])

print("\nFirst 10 actual values:")
print(y_test.values[:10])

First 10 predicted values:
[0 1 0 1 1 0 1 0 0 0]

First 10 actual values:
[0 1 0 1 0 0 1 0 0 0]

In [56]:
y_prob_logistic = logistic_model.predict_proba(X_test_scaled)[:, 1]

In [58]:
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef
)

In [60]:
log_accuracy = accuracy_score(y_test, y_pred_logistic)
log_auc = roc_auc_score(y_test, y_prob_logistic)
log_precision = precision_score(y_test, y_pred_logistic)
log_recall = recall_score(y_test, y_pred_logistic)
log_f1 = f1_score(y_test, y_pred_logistic)
log_mcc = matthews_corrcoef(y_test, y_pred_logistic)

In [62]:
print("Logistic Regression Results")
print("---------------------------")
print("Accuracy :", round(log_accuracy, 4))
print("AUC      :", round(log_auc, 4))
print("Precision:", round(log_precision, 4))
print("Recall   :", round(log_recall, 4))
print("F1 Score :", round(log_f1, 4))
print("MCC      :", round(log_mcc, 4))

Logistic Regression Results
---------------------------
Accuracy : 0.9649
AUC      : 0.996
Precision: 0.975
Recall   : 0.9286
F1 Score : 0.9512
MCC      : 0.9245

In [64]:
from sklearn.metrics import confusion_matrix, classification_report

cm_logistic = confusion_matrix(y_test, y_pred_logistic)

print("Confusion Matrix:")
print(cm_logistic)

Confusion Matrix:
[[71  1]
 [ 3 39]]

In [66]:
print("Classification Report:")
print(
    classification_report(
        y_test,
        y_pred_logistic,
        target_names=["Benign", "Malignant"]
    )
)

Classification Report:
              precision    recall  f1-score   support

      Benign       0.96      0.99      0.97        72
   Malignant       0.97      0.93      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

In [68]:
model_results = []

In [70]:
model_results.append({
    "Model": "Logistic Regression",
    "Accuracy": log_accuracy,
    "AUC": log_auc,
    "Precision": log_precision,
    "Recall": log_recall,
    "F1": log_f1,
    "MCC": log_mcc
})

In [72]:
import pandas as pd

results_df = pd.DataFrame(model_results)
results_df

,Model,Accuracy,AUC,Precision,Recall,F1,MCC
0,Logistic Regression,0.964912,0.996032,0.975,0.928571,0.95122,0.924518

Decision Tree Classifier

In [74]:
from sklearn.tree import DecisionTreeClassifier

In [76]:
decision_tree_model = DecisionTreeClassifier(
    random_state=42
)

In [78]:
decision_tree_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [80]:
y_pred_dt = decision_tree_model.predict(X_test)

In [82]:
y_prob_dt = decision_tree_model.predict_proba(X_test)[:, 1]

In [84]:
dt_accuracy = accuracy_score(y_test, y_pred_dt)
dt_auc = roc_auc_score(y_test, y_prob_dt)
dt_precision = precision_score(y_test, y_pred_dt)
dt_recall = recall_score(y_test, y_pred_dt)
dt_f1 = f1_score(y_test, y_pred_dt)
dt_mcc = matthews_corrcoef(y_test, y_pred_dt)

In [86]:
print("Decision Tree Results")
print("---------------------")
print("Accuracy :", round(dt_accuracy, 4))
print("AUC      :", round(dt_auc, 4))
print("Precision:", round(dt_precision, 4))
print("Recall   :", round(dt_recall, 4))
print("F1 Score :", round(dt_f1, 4))
print("MCC      :", round(dt_mcc, 4))

Decision Tree Results
---------------------
Accuracy : 0.9298
AUC      : 0.9246
Precision: 0.9048
Recall   : 0.9048
F1 Score : 0.9048
MCC      : 0.8492

In [88]:
cm_dt = confusion_matrix(y_test, y_pred_dt)

print("Decision Tree Confusion Matrix:")
print(cm_dt)

Decision Tree Confusion Matrix:
[[68  4]
 [ 4 38]]

In [90]:
print("Decision Tree Classification Report:")

print(
    classification_report(
        y_test,
        y_pred_dt,
        target_names=["Benign", "Malignant"]
    )
)

Decision Tree Classification Report:
              precision    recall  f1-score   support

      Benign       0.94      0.94      0.94        72
   Malignant       0.90      0.90      0.90        42

    accuracy                           0.93       114
   macro avg       0.92      0.92      0.92       114
weighted avg       0.93      0.93      0.93       114

In [92]:
model_results.append({
    "Model": "Decision Tree",
    "Accuracy": dt_accuracy,
    "AUC": dt_auc,
    "Precision": dt_precision,
    "Recall": dt_recall,
    "F1": dt_f1,
    "MCC": dt_mcc
})

In [94]:
results_df = pd.DataFrame(model_results)
results_df

,Model,Accuracy,AUC,Precision,Recall,F1,MCC
0,Logistic Regression,0.964912,0.996032,0.975000,0.928571,0.951220,0.924518
1,Decision Tree,0.929825,0.924603,0.904762,0.904762,0.904762,0.849206

K-Nearest Neighbors (KNN}

In [96]:
from sklearn.neighbors import KNeighborsClassifier

In [98]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [100]:
knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [102]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [104]:
y_prob_knn = knn_model.predict_proba(X_test_scaled)[:, 1]

In [106]:
knn_accuracy = accuracy_score(y_test, y_pred_knn)
knn_auc = roc_auc_score(y_test, y_prob_knn)
knn_precision = precision_score(y_test, y_pred_knn)
knn_recall = recall_score(y_test, y_pred_knn)
knn_f1 = f1_score(y_test, y_pred_knn)
knn_mcc = matthews_corrcoef(y_test, y_pred_knn)

In [108]:
print("KNN Results")
print("---------------------")
print("Accuracy :", round(knn_accuracy, 4))
print("AUC      :", round(knn_auc, 4))
print("Precision:", round(knn_precision, 4))
print("Recall   :", round(knn_recall, 4))
print("F1 Score :", round(knn_f1, 4))
print("MCC      :", round(knn_mcc, 4))

KNN Results
---------------------
Accuracy : 0.9561
AUC      : 0.9823
Precision: 0.9744
Recall   : 0.9048
F1 Score : 0.9383
MCC      : 0.9058

In [110]:
cm_knn = confusion_matrix(y_test, y_pred_knn)

print("KNN Confusion Matrix:")
print(cm_knn)

KNN Confusion Matrix:
[[71  1]
 [ 4 38]]

In [112]:
print("KNN Classification Report:")

print(
    classification_report(
        y_test,
        y_pred_knn,
        target_names=["Benign", "Malignant"]
    )
)

KNN Classification Report:
              precision    recall  f1-score   support

      Benign       0.95      0.99      0.97        72
   Malignant       0.97      0.90      0.94        42

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

In [114]:
model_results.append({
    "Model": "KNN",
    "Accuracy": knn_accuracy,
    "AUC": knn_auc,
    "Precision": knn_precision,
    "Recall": knn_recall,
    "F1": knn_f1,
    "MCC": knn_mcc
})

In [116]:
results_df = pd.DataFrame(model_results)
results_df

,Model,Accuracy,AUC,Precision,Recall,F1,MCC
0,Logistic Regression,0.964912,0.996032,0.975000,0.928571,0.951220,0.924518
1,Decision Tree,0.929825,0.924603,0.904762,0.904762,0.904762,0.849206
2,KNN,0.956140,0.982308,0.974359,0.904762,0.938272,0.905824

Gaussian Naive Bayes

In [118]:
from sklearn.naive_bayes import GaussianNB

In [120]:
nb_model = GaussianNB()

In [122]:
nb_model.fit(X_train_scaled, y_train)

GaussianNB()

In [124]:
y_pred_nb = nb_model.predict(X_test_scaled)

In [126]:
y_prob_nb = nb_model.predict_proba(X_test_scaled)[:, 1]

In [128]:
nb_accuracy = accuracy_score(y_test, y_pred_nb)
nb_auc = roc_auc_score(y_test, y_prob_nb)
nb_precision = precision_score(y_test, y_pred_nb)
nb_recall = recall_score(y_test, y_pred_nb)
nb_f1 = f1_score(y_test, y_pred_nb)
nb_mcc = matthews_corrcoef(y_test, y_pred_nb)

In [130]:
print("Naive Bayes Results")
print("---------------------")
print("Accuracy :", round(nb_accuracy, 4))
print("AUC      :", round(nb_auc, 4))
print("Precision:", round(nb_precision, 4))
print("Recall   :", round(nb_recall, 4))
print("F1 Score :", round(nb_f1, 4))
print("MCC      :", round(nb_mcc, 4))

Naive Bayes Results
---------------------
Accuracy : 0.9211
AUC      : 0.9891
Precision: 0.9231
Recall   : 0.8571
F1 Score : 0.8889
MCC      : 0.8292

In [132]:
cm_nb = confusion_matrix(y_test, y_pred_nb)

print("Naive Bayes Confusion Matrix:")
print(cm_nb)

Naive Bayes Confusion Matrix:
[[69  3]
 [ 6 36]]

In [134]:
print("Naive Bayes Classification Report:")

print(
    classification_report(
        y_test,
        y_pred_nb,
        target_names=["Benign", "Malignant"]
    )
)

Naive Bayes Classification Report:
              precision    recall  f1-score   support

      Benign       0.92      0.96      0.94        72
   Malignant       0.92      0.86      0.89        42

    accuracy                           0.92       114
   macro avg       0.92      0.91      0.91       114
weighted avg       0.92      0.92      0.92       114

In [136]:
model_results.append({
    "Model": "Naive Bayes",
    "Accuracy": nb_accuracy,
    "AUC": nb_auc,
    "Precision": nb_precision,
    "Recall": nb_recall,
    "F1": nb_f1,
    "MCC": nb_mcc
})

In [138]:
results_df = pd.DataFrame(model_results)
results_df

,Model,Accuracy,AUC,Precision,Recall,F1,MCC
0,Logistic Regression,0.964912,0.996032,0.975000,0.928571,0.951220,0.924518
1,Decision Tree,0.929825,0.924603,0.904762,0.904762,0.904762,0.849206
2,KNN,0.956140,0.982308,0.974359,0.904762,0.938272,0.905824
3,Naive Bayes,0.921053,0.989087,0.923077,0.857143,0.888889,0.829162

Random Forest

In [140]:
from sklearn.ensemble import RandomForestClassifier

In [142]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [144]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [146]:
y_pred_rf = rf_model.predict(X_test)

In [148]:
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

In [150]:
rf_accuracy = accuracy_score(y_test, y_pred_rf)
rf_auc = roc_auc_score(y_test, y_prob_rf)
rf_precision = precision_score(y_test, y_pred_rf)
rf_recall = recall_score(y_test, y_pred_rf)
rf_f1 = f1_score(y_test, y_pred_rf)
rf_mcc = matthews_corrcoef(y_test, y_pred_rf)

In [152]:
print("Random Forest Results")
print("---------------------")
print("Accuracy :", round(rf_accuracy, 4))
print("AUC      :", round(rf_auc, 4))
print("Precision:", round(rf_precision, 4))
print("Recall   :", round(rf_recall, 4))
print("F1 Score :", round(rf_f1, 4))
print("MCC      :", round(rf_mcc, 4))

Random Forest Results
---------------------
Accuracy : 0.9737
AUC      : 0.9929
Precision: 1.0
Recall   : 0.9286
F1 Score : 0.963
MCC      : 0.9442

In [154]:
cm_rf = confusion_matrix(y_test, y_pred_rf)

print("Random Forest Confusion Matrix:")
print(cm_rf)

Random Forest Confusion Matrix:
[[72  0]
 [ 3 39]]

In [156]:
print("Random Forest Classification Report:")

print(
    classification_report(
        y_test,
        y_pred_rf,
        target_names=["Benign", "Malignant"]
    )
)

Random Forest Classification Report:
              precision    recall  f1-score   support

      Benign       0.96      1.00      0.98        72
   Malignant       1.00      0.93      0.96        42

    accuracy                           0.97       114
   macro avg       0.98      0.96      0.97       114
weighted avg       0.97      0.97      0.97       114

In [158]:
model_results.append({
    "Model": "Random Forest",
    "Accuracy": rf_accuracy,
    "AUC": rf_auc,
    "Precision": rf_precision,
    "Recall": rf_recall,
    "F1": rf_f1,
    "MCC": rf_mcc
})

In [160]:
results_df = pd.DataFrame(model_results)

results_df

,Model,Accuracy,AUC,Precision,Recall,F1,MCC
0,Logistic Regression,0.964912,0.996032,0.975000,0.928571,0.951220,0.924518
1,Decision Tree,0.929825,0.924603,0.904762,0.904762,0.904762,0.849206
2,KNN,0.956140,0.982308,0.974359,0.904762,0.938272,0.905824
3,Naive Bayes,0.921053,0.989087,0.923077,0.857143,0.888889,0.829162
4,Random Forest,0.973684,0.992890,1.000000,0.928571,0.962963,0.944155

In [162]:
results_display = results_df.copy()

numeric_columns = [
    "Accuracy",
    "AUC",
    "Precision",
    "Recall",
    "F1",
    "MCC"
]

results_display[numeric_columns] = results_display[numeric_columns].round(4)

results_display

                 Model  Accuracy     AUC  Precision  Recall      F1     MCC
0  Logistic Regression    0.9649  0.9960     0.9750  0.9286  0.9512  0.9245
1        Decision Tree    0.9298  0.9246     0.9048  0.9048  0.9048  0.8492
2                  KNN    0.9561  0.9823     0.9744  0.9048  0.9383  0.9058
3          Naive Bayes    0.9211  0.9891     0.9231  0.8571  0.8889  0.8292
4        Random Forest    0.9737  0.9929     1.0000  0.9286  0.9630  0.9442

A sorted comparison

In [164]:
results_df.sort_values(
    by="Accuracy",
    ascending=False
)

,Model,Accuracy,AUC,Precision,Recall,F1,MCC
4,Random Forest,0.973684,0.992890,1.000000,0.928571,0.962963,0.944155
0,Logistic Regression,0.964912,0.996032,0.975000,0.928571,0.951220,0.924518
2,KNN,0.956140,0.982308,0.974359,0.904762,0.938272,0.905824
1,Decision Tree,0.929825,0.924603,0.904762,0.904762,0.904762,0.849206
3,Naive Bayes,0.921053,0.989087,0.923077,0.857143,0.888889,0.829162

Observations

Based on the actual results:

Logistic Regression: Strong overall performance with 96.49% accuracy and the highest AUC of 99.60%. It achieved high precision and recall, showing excellent ability to distinguish benign and malignant cases.

Decision Tree: Achieved 92.98% accuracy. Its performance was lower than Logistic Regression, KNN and Random Forest, with comparatively lower AUC and MCC scores.

KNN: Performed strongly with 95.61% accuracy and 97.44% precision. Scaling helped KNN because it relies on distances between observations.

Naive Bayes: Achieved 92.11% accuracy and a strong AUC of 98.91%. However, it had the lowest recall of 85.71%, indicating that it missed more malignant cases than the other models.

Random Forest: Achieved the highest accuracy of 97.37%, perfect precision of 100%, highest F1 score of 96.30%, and highest MCC of 0.9442. It produced the strongest overall performance among the evaluated models.

Random Forest: Random Forest is selected as the overall best-performing model because it achieved the highest accuracy, precision, F1 score and MCC while maintaining high recall and AUC.

Save test_data.csv

In [166]:
test_data = X_test.copy()

test_data["diagnosis"] = y_test.values

print(test_data.shape)
test_data.head()

(114, 31)

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis
120,11.41,10.82,73.34,403.3,0.09373,0.06685,0.03512,0.02623,0.1667,0.06113,...,15.97,83.74,510.5,0.1548,0.2390,0.21020,0.08958,0.3016,0.08523,0
250,20.94,23.56,138.90,1364.0,0.10070,0.16060,0.27120,0.13100,0.2205,0.05898,...,27.00,165.30,2010.0,0.1211,0.3172,0.69910,0.21050,0.3126,0.07849,1
375,16.17,16.07,106.30,788.5,0.09880,0.14380,0.06651,0.05397,0.1990,0.06572,...,19.14,113.10,861.5,0.1235,0.2550,0.21140,0.12510,0.3153,0.08960,0
99,14.42,19.77,94.48,642.5,0.09752,0.11410,0.09388,0.05839,0.1879,0.06390,...,30.86,109.50,826.4,0.1431,0.3026,0.31940,0.15650,0.2718,0.09353,1
455,13.38,30.72,86.34,557.2,0.09245,0.07426,0.02819,0.03264,0.1375,0.06016,...,41.61,96.69,705.6,0.1172,0.1421,0.07003,0.07763,0.2196,0.07675,0

In [168]:
test_data.to_csv("test_data.csv", index=False)

print("test_data.csv saved successfully.")

test_data.csv saved successfully.

In [170]:
import joblib
import os

In [172]:
os.makedirs("model", exist_ok=True)

In [174]:
joblib.dump(
    logistic_model,
    "model/logistic_regression.pkl"
)

joblib.dump(
    decision_tree_model,
    "model/decision_tree.pkl"
)

joblib.dump(
    knn_model,
    "model/knn.pkl"
)

joblib.dump(
    nb_model,
    "model/naive_bayes.pkl"
)

joblib.dump(
    rf_model,
    "model/random_forest.pkl"
)

['model/random_forest.pkl']

In [176]:
X_train_scaled

array([[ 0.51855873,  0.89182579,  0.4246317 , ..., -0.23574392,
         0.05456632,  0.02183673],
       [-0.51636409, -1.63971029, -0.54134872, ..., -0.32320788,
        -0.13757624, -0.90440164],
       [-0.36811839,  0.45551496, -0.38824993, ..., -0.89082504,
        -0.675893  , -0.14401559],
       ...,
       [-0.32616206,  1.33280304, -0.38905998, ..., -0.84289958,
        -0.96490082, -1.16888375],
       [ 0.00948859,  0.25952507,  0.00786279, ...,  0.27571059,
        -0.60284707, -0.30545988],
       [ 0.80945595,  0.36918608,  0.79320285, ...,  1.00657384,
        -0.46151907, -0.44817001]])

In [178]:
joblib.dump(
    scaler,
    "model/scaler.pkl"
)

['model/scaler.pkl']

In [180]:
print(os.listdir("model"))

['logistic_regression.pkl', 'decision_tree.pkl', 'knn.pkl', 'naive_bayes.pkl', 'random_forest.pkl', 'scaler.pkl']

In [182]:
print("Test data:", test_data.shape)

Test data: (114, 31)